### ISSUE TITLE
[bal-select] Default Value not displayed

### ISSUE THREAD

**Issue by GinaBiondo-aperto** [baloise-incubator/design-system#329]
## Detailed description

- on load, the default selected value for the 'bal-select' is missing
- therefore the closed dropdown is displayed as empty

<img width="600" alt="Bildschirmfoto 2022-08-09 um 13 58 32" src="https://user-images.githubusercontent.com/72393447/183641675-24fa4549-911f-4449-b39b-eacc02989c05.png">
<img width="595" alt="Bildschirmfoto 2022-08-09 um 13 58 52" src="https://user-images.githubusercontent.com/72393447/183641703-9eadc691-0814-4900-a95d-3beb91156b3d.png">

**Comment by hirsch88** [comment]
I think that is fixed

**Comment by joachimprinzbach** [comment]
I will close this then for now, was quite old - just not part of the board

**Comment by rainerblumenthal** [comment]
@joachimprinzbach Did you check this on a real mobile device ? 

https://baloise-reb.dev.aperto.systems/baloise-qa/de/qa/Sprints/Sprint-11/Blog-Magazine-Teaser.html

We still face the problem - and we have included the latest DS.

**Comment by joachimprinzbach** [comment]
@rainerblumenthal no did not - as we thaught it was already fixed. Will reopen it, thanks for the hint.

**Comment by rainerblumenthal** [comment]
![image](https://user-images.githubusercontent.com/17472781/191462153-49a872da-6e8f-41bb-9e1d-280d2c00f09d.png)

It still does not work on a real mobile device.

https://baloise-reb.dev.aperto.systems/baloise-qa/home.html

Our servers are reachable via HTACCESS - if you want to retest there, they can be reached by you. Ifyou need HTACCESSLogin just Slack me.

**Comment by rainerblumenthal** [comment]
**Max sagt:** 
Habe es nochmal getestet… ist ein fehler in den bal-tabs und nur onload, wenn du resized oder das gerät drehst und wieder zurück in den mobile viewport gehst passt es. Ist aber definitiv ein DS Issue.

https://baloise-reb.dev.aperto.systems/baloise-qa/de/qa/Sprints/Sprint-11/tab-component.html

**Comment by hirsch88** [comment]
@rainerblumenthal this is a different bug could you create a new GitHub issue for that and please write in English so that everybody underdstands it
